name: dotnet

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.3
        with:
          versionSpec: "5.x"

      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.3

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.401

      - uses: actions/cache@v2
        env:
          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - run: dotnet restore

      - run: dotnet build --configuration Release --no-restore

      - run: |
          dotnet test \
            --configuration Release \
            --no-build \
            --no-restore \
            -p:CollectCoverage=true \
            -p:CoverletOutputFormat=opencover \
            -p:Exclude="[JsonLD.Test*]*"

      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: NuGet Pack
        run: |
          dotnet pack \
            --include-source \
            --configuration Release \
            --no-build \
            --no-restore \
            -p:PackageVersion="${{ steps.gitversion.outputs.fullSemVer }}" \
            src/json-ld.net/json-ld.net.csproj \
            --output nugets/

      - uses: actions/upload-artifact@v2
        with:
          name: nugets
          path: nugets
